- .github/workflows/release.yml
- .m2/settings.xml
- README.md
- pom.xml
I followed https://dzone.com/articles/publish-your-artifacts-to-maven-central.
I distributed the GPG keys to hkp://pgp.mit.edu according to https://blog.sonatype.com/2010/01/how-to-generate-pgp-signatures-with-maven/#BLOG-108SignArtifacts,IntegrateMavenandGPG-DistributeYouPublicKey.
I have no idea whether it works yet 😁
> Releasing to Maven Central

- pom.xml
According to https://stackoverflow.com/a/56664610/1225328
> Adding missing dependency

- pom.xml
- qudini-reactive-example/pom.xml
- qudini-reactive-logging/pom.xml
- qudini-reactive-metrics/pom.xml
- qudini-reactive-sqs/pom.xml
- qudini-reactive-tests/pom.xml
- qudini-reactive-utils/pom.xml
> Trying release driven approach

- pom.xml
- qudini-reactive-sqs/pom.xml
Updating to Spring Boot 2.3 and SQS 2.13
> Updating dependencies

- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/ReactiveLoggingAutoConfiguration.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/DefaultCorrelationIdForwarder.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/LoggingContextFilter.java
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/web/DefaultCorrelationIdForwarderTest.java
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/web/LoggingContextFilterTest.java
> Fixing correlationIdForwarder

- qudini-reactive-metrics/README.md
- qudini-reactive-metrics/src/main/java/com/qudini/reactive/metrics/ReactiveMetricsAutoConfiguration.java
- qudini-reactive-metrics/src/main/java/com/qudini/reactive/metrics/buildinfo/BuildInfoMeterBinder.java
> Build info gauge name parameterisable

- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/Trackers.java
- qudini-reactive-utils/src/main/java/com/qudini/reactive/utils/ReactiveUtilsAutoConfiguration.java
- qudini-reactive-utils/src/main/java/com/qudini/reactive/utils/metadata/DefaultMetadataService.java
Useful for integration tests, where Sentry and NewRelic aren't plugged in.
> Initialising trackers only if instantiated

- qudini-reactive-logging/README.md
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/ReactiveLoggingAutoConfiguration.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/QudiniJsonLayout.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/QudiniLogEvent.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/Tracker.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/Trackers.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/trackers/NewRelicTracker.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/log4j2/trackers/SentryTracker.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/DefaultLoggingContextExtractor.java
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/web/DefaultLoggingContextExtractorTest.java
> Fixing Sentry's reporting

- qudini-reactive-graphql/src/main/java/com/qudini/reactive/graphql/http/GraphQLHandler.java
- qudini-reactive-logging/README.md
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/Log.java
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/LogTest.java
Making the logging MDC available when executing a GraphQL query.
> GraphQL logs

- pom.xml
https://github.com/spring-projects/spring-boot/releases/tag/v2.6.2
> Spring Boot 2.6.2

- pom.xml
- qudini-reactive-example/pom.xml
- qudini-reactive-logging/README.md
- Spring Boot [v2.6.3](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.3)
- NewRelic [v.7.5.0](https://github.com/newrelic/newrelic-java-agent/releases/tag/v7.5.0)
- Sentry [v5.5.3](https://github.com/getsentry/sentry-java/releases/tag/5.5.3)
> Spring Boot 2.6.3

- qudini-reactive-security/src/main/java/com/qudini/reactive/security/web/AuthenticatingFilter.java
- qudini-reactive-security/src/test/java/com/qudini/reactive/security/web/AuthenticatingFilterTest.java
So that `@WithMockUser` can still be used in integration tests.
> Do not overwrite existing auth if any

- qudini-reactive-utils/src/main/java/com/qudini/reactive/utils/ReactiveUtilsAutoConfiguration.java
Closes https://github.com/qudini/qudini-reactive/issues/98
> Clock bean

- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/Log.java
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/LogTest.java
Fixes https://github.com/qudini/qudini-reactive/issues/101
> Log.then(Runnable)

- qudini-reactive-utils/src/main/java/com/qudini/reactive/utils/MoreCollectors.java
- qudini-reactive-utils/src/test/java/com/qudini/reactive/utils/MoreCollectorsTest.java
Fixes https://github.com/qudini/qudini-reactive/issues/102
> MoreCollectors

- pom.xml
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/CorrelationIdForwarder.java
- qudini-reactive-security/README.md
- qudini-reactive-security/pom.xml
- qudini-reactive-security/src/main/java/com/qudini/reactive/security/ReactiveSecurityAutoConfiguration.java
Fixes https://github.com/qudini/qudini-reactive/issues/100
> Installing the Bouncy Castle provider

- qudini-reactive-security/src/main/java/com/qudini/reactive/security/support/rsa/OpenSsh.java
- qudini-reactive-security/src/main/java/com/qudini/reactive/security/support/rsa/OpenSshException.java
- qudini-reactive-security/src/main/java/com/qudini/reactive/security/support/rsa/OpenSshKeyPair.java
- qudini-reactive-security/src/test/java/com/qudini/reactive/security/support/rsa/OpenSshTest.java
Fixes https://github.com/qudini/qudini-reactive/issues/99
> OpenSSH utility

- pom.xml
- qudini-reactive-graphql/src/main/java/com/qudini/reactive/graphql/http/LoggingContextAwareExceptionHandler.java
See https://github.com/qudini/gom/releases/tag/v8.0.0
> GOM v8.0.0

- pom.xml
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/log4j2/QudiniJsonLayoutTest.java
- https://github.com/spring-projects/spring-boot/releases/tag/v2.6.5
- https://github.com/getsentry/sentry-java/releases/tag/5.7.0
> Spring Boot v2.6.5

- pom.xml
https://github.com/spring-projects/spring-boot/releases/tag/v2.6.6
> Spring Boot v2.6.6

- pom.xml
See https://github.com/spring-projects/spring-boot/issues/30986
> Lombok before Spring Boot Configuration Processor

- pom.xml
- qudini-reactive-example/pom.xml
- qudini-reactive-example/src/main/resources/META-INF/native-image/native-image.properties
- qudini-reactive-graphql/src/main/java/com/qudini/reactive/graphql/ReactiveGraphQLAutoConfiguration.java
- qudini-reactive-graphql/src/main/java/com/qudini/reactive/graphql/http/LoggingContextAwareExceptionHandler.java
- qudini-reactive-graphql/src/main/resources/META-INF/spring.factories
- qudini-reactive-graphql/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/ReactiveLoggingAutoConfiguration.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/ExceptionHandlingFilter.java
- qudini-reactive-logging/src/main/java/com/qudini/reactive/logging/web/HttpAwareLoggingContextExtractor.java
- qudini-reactive-logging/src/main/resources/META-INF/spring.factories
- qudini-reactive-logging/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- qudini-reactive-logging/src/test/java/com/qudini/reactive/logging/web/HttpAwareLoggingContextExtractorTest.java
- qudini-reactive-metrics/src/main/java/com/qudini/reactive/metrics/ReactiveMetricsAutoConfiguration.java
- qudini-reactive-metrics/src/main/resources/META-INF/spring.factories
- qudini-reactive-metrics/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- qudini-reactive-security/src/main/java/com/qudini/reactive/security/ReactiveSecurityAutoConfiguration.java
- qudini-reactive-security/src/main/resources/META-INF/spring.factories
- qudini-reactive-security/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- qudini-reactive-security/src/test/java/com/qudini/reactive/security/web/AccessDeniedExceptionHandlingFilterTest.java
- qudini-reactive-sqs/src/main/java/com/qudini/reactive/sqs/ReactiveSqsAutoConfiguration.java
- qudini-reactive-sqs/src/main/java/com/qudini/reactive/sqs/listener/SqsListeners.java
- qudini-reactive-sqs/src/main/resources/META-INF/spring.factories
- qudini-reactive-sqs/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
- qudini-reactive-utils/src/main/java/com/qudini/reactive/utils/ReactiveUtilsAutoConfiguration.java
- qudini-reactive-utils/src/main/resources/META-INF/spring.factories
- qudini-reactive-utils/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Updated dependencies to Spring Boot 3 and fix security vulnerabilities.
Squashed commits form #166
> Update to Spring Boot 3

- pom.xml
- qudini-reactive-metrics/pom.xml
Include prometheus dependency on qudini-reactive-metrics
> Fix prometheus dependency

- pom.xml
Updates:
* Spring Boot 3.2.2
* NewRelic 8.9.1
* Other library updates
> Update to Spring Boot 3.2.2
